### ISSUE TITLE
incompatible with ember-cli-app-version

### ISSUE THREAD

**Issue by basz** [mansona/ember-get-config#47]
ember-cli-app-version changes the environment object; APP['version'] is set. 

ember-get-config reads it before that change I think.

so in an app this works;
```
import config from '../config/environment';
console.log(config.APP['version']);
```
while this does not;
```
import config from 'ember-get-config';
console.log(config.APP['version']);
```

oooor,... i could be doing it wrong...

**Comment by bertdeblock** [comment]
This would be solved by https://github.com/mansona/ember-get-config/pull/45.

**Comment by mansona** [comment]
This should be fixed now in https://github.com/mansona/ember-get-config/releases/tag/v2.1.0 👍

**Comment by basz** [comment]
hi, i've tested a bit more.

When using embroider this still happens

**Comment by bertdeblock** [comment]
@basz That's because under Embroider, a compat adapter is used instead of `ember-get-config` itself.
We should PR that the compat adapter is not used when `embet-get-config` >= v2.1 is detected I think.

**Comment by bertdeblock** [comment]
Forgot to mention, you can also disable the compat adapter in your project for now.

**Comment by bertdeblock** [comment]
The adapter is now disabled in Embroider v1.8.1:
https://github.com/embroider-build/embroider/releases/tag/v1.8.1
